name: data_manage
description: Data structures and typedefs for convenient and advanced processing of your data.
version: 1.3.8
repository: https://github.com/nogipx/data_manage

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.3
  freezed:
  build_runner:
