name: data_manage
description: Data structures and typedefs for convenient and advanced processing of your data.
version: 2.0.0
repository: https://github.com/nogipx/data_manage

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  fast_immutable_collections: ^10.2.2
  freezed_annotation: ^2.4.1

dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  freezed:
  build_runner:
